MyTrojan/MyTrojan/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', views.Index.as_view(), name="index"),
    path('user/', include("user.urls"))
]
handler404 = views.page_not_found

MyTrojan/apps/user/urls.py
from django.urls import path, re_path
from . import views

app_name = 'user'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.Register.as_view(), name='register'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('home/', views.HomePage.as_view(), name="home"),
    path('verify_email/<email>/', views.verify_email, name='verify_email'),
    path('verify_username/<username>/', views.verify_username, name='verify_username'),
    path('get_user_data/', views.get_user_data, name="get_user_data"),
    path('set_password/', views.set_password, name="change_password")
]

MyTrojan/apps/user/models.py
from django.utils import timezone

import hashlib
from django.contrib.auth.models import AbstractUser, UserManager as _UserManager
from django.db import models
import logging

log = logging.getLogger("trojan")


class MyUserManage(_UserManager):
    def _create_user(self, username, email, password, **extra_fields):
        if not username:
            raise ValueError('The given username must be set')
        email = self.normalize_email(email)
        username = self.model.normalize_username(username)
        user = self.model(username=username, email=email, **extra_fields)
        password_bak = password
        user.set_password(password)
        user.save(using=self._db, origin_password=password_bak)
        return user


class Users(AbstractUser):
    password = models.CharField(max_length=128, db_column="user_password")
    sha224 = models.CharField(max_length=56, db_index=True, db_column="password", editable=False, blank=True)  # hash密码
    quota = models.BigIntegerField(default=0)
    download = models.BigIntegerField(default=0)
    upload = models.BigIntegerField(default=0)
    objects = MyUserManage()
    first_name = None
    last_name = None

    class Meta:
        db_table = 'users'
        verbose_name = "user"
        verbose_name_plural = 'users'

    def __str__(self):
        return self.username + "," + self.email + "," + "1" if self.is_staff else "0"

    # 最好放到前台去加密
    def save(self, *args, **kwargs):
        if kwargs.get("origin_password"):
            origin_password = kwargs.pop("origin_password")
            a = hashlib.sha224()
            a.update((self.username + ":" + origin_password).encode("utf-8"))
            self.sha224 = a.hexdigest()
            logging.info('hash' + ':' + self.sha224)
        super().save(*args, **kwargs)

MyTrojan/apps/user/forms.py
from django.contrib.auth import login
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.db.models import Q
from django.forms import forms

from django import forms

from .custom_tool.UsernameValidate import validate_username
from user.models import Users

USER_SESSION_EXPIRES = 60 * 60 * 12


class LoginForm(forms.Form):
    username = forms.CharField(label="用户名/邮箱", max_length=20, min_length=6, validators=[validate_username])
    password = forms.CharField(label="密码", min_length=6, max_length=25,
                               error_messages={"min_length": "密码长度最短7", "max_length": "密码长度最高8"})

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(LoginForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get("username")
        password = cleaned_data.get("password")
        remember = cleaned_data.get("remember_me")
        user_queryset = Users.objects.filter(Q(username=username) | Q(email=username))
        if user_queryset:
            user = user_queryset.first()
            if user.check_password(password):
                if remember:
                    self.request.session.set_expiry(None)
                else:
                    self.request.session.set_expiry(USER_SESSION_EXPIRES)
                login(self.request, user)
            else:
                raise forms.ValidationError("密码错误")
        else:
            raise forms.ValidationError("账户不存在")


class RegisterForm(forms.Form):
    username = forms.CharField(min_length=6, max_length=20, validators=[UnicodeUsernameValidator])
    email = forms.EmailField(max_length=150)
    password = forms.CharField(label="密码", min_length=6, max_length=25)
    repeat_password = forms.CharField(label="确认密码")

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get("username")
        password = cleaned_data.get("password")
        repeat_password = cleaned_data.get("repeat_password")
        email = cleaned_data.get("email")
        if not password:
            raise forms.ValidationError("密码为空")
        if password != repeat_password:
            raise forms.ValidationError("两次密码输入不一致")
        users = Users.objects.filter(Q(username=username) | Q(email=email)).first()
        if users:
            if username == users.username:
                raise forms.ValidationError("用户名已存在")
            if email == users.email:
                raise forms.ValidationError("邮箱已被注册")

MyTrojan/apps/user/views.py
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse

from django.views import View
import json

from user.models import Users
from .forms import LoginForm, RegisterForm
from user.custom_tool.json_response import to_json_data
from user.custom_tool.res_code import Code, error_map


class LoginView(View):
    def get(self, request):
        # if request.session.exists("session_key"):
        #     return render(request, 'user/home.html')
        if request.user.is_authenticated:
            return redirect(reverse("user:home"))
        return render(request, 'user/login.html')

    def post(self, request):
        json_data = request.body
        if not json_data:
            return to_json_data(errno=Code.PARAMERR, msg=error_map[Code.PARAMERR])
        dict_data = json.loads(json_data.decode('utf8'))
        form = LoginForm(data=dict_data, request=request)
        if form.is_valid():
            return to_json_data(msg="登录成功")
        else:
            error_map_list = []
            for item in form.errors.get_json_data().values():
                error_map_list.append(item[0].get('message'))
            return to_json_data(errno=Code.PARAMERR, msg="&".join(error_map_list))


class Register(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect(reverse("user:home"))
        return render(request, 'user/register.html')

    def post(self, request):
        json_data = request.body
        if not json_data:
            return to_json_data(errno=Code.PARAMERR, msg=error_map[Code.PARAMERR])
        # 将json转化为dict
        dict_data = json.loads(json_data.decode('utf8'))
        form = RegisterForm(data=dict_data)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            email = form.cleaned_data.get('email')
            user = Users.objects.create_user(username=username, password=password, email=email, quota=1024000000)
            login(request, user)
            return to_json_data(msg="注册成功")
        else:
            # 定义一个错误信息列表
            err_msg_list = []
            for item in form.errors.get_json_data().values():
                err_msg_list.append(item[0].get('message'))
            err_msg_str = '&'.join(err_msg_list)
            return to_json_data(errno=Code.PARAMERR, msg=err_msg_str)


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect(reverse("user:home"))


class HomePage(View):
    def get(self, request):
        if request.user.is_anonymous:
            return redirect(reverse("user:login"))
        left = request.user.quota - request.user.upload - request.user.download
        if left < 0:
            left = 0
        if request.user.quota == -1:
            left = 'Infinite'

        return render(request, "user/home.html",
                      context={
                          "left": left})


def verify_email(request, email):
    if request.method != 'GET':
        return to_json_data(Code.METHERR, "错误")
    return to_json_data(data={"email": email, "count": Users.objects.filter(email=email).count()})


def verify_username(request, username):
    if request.method != 'GET':
        return to_json_data(Code.METHERR, "错误")
    return to_json_data(data={"username": username, "count": Users.objects.filter(username=username).count()})


def get_user_data(request):
    if request.user.is_anonymous:
        return to_json_data(Code.ROLEERR, msg="用户未登录")
    left = request.user.quota - request.user.upload - request.user.download
    if left < 0:
        left = 0
    if request.user.quota == -1:
        left = 'Infinite'
    return to_json_data(
        data={'quota': 'Infinite' if request.user.quota == -1 else request.user.quota, 'upload': request.user.upload,
              'download': request.user.download,
              'left': left,
              'username': request.user.username, 'email': request.user.email})


def set_password(request):
    if request.user.is_anonymous:
        return to_json_data(Code.ROLEERR, msg="用户未登录")
    username = request.user.username
    json_data = request.body
    if not json_data:
        return to_json_data(errno=Code.PARAMERR, msg=error_map[Code.PARAMERR])
    dict_data = json.loads(json_data.decode('utf8'))
    try:
        if dict_data["new_password"] != dict_data["repeat_password"]:
            return to_json_data(errno=Code.PARAMERR, msg="两次输入不一致")
        user = authenticate(username=username, password=dict_data["old_password"])
        if user:
            user.set_password(dict_data["new_password"])
            user.save(origin_password=dict_data["new_password"])
            return to_json_data(msg="修改成功")
        return to_json_data(Code.PWDERR, msg="密码错误")
    except:
        return to_json_data(Code.PARAMERR, msg="参数错误")

MyTrojan/templates/user/home.html
{% extends "base/base.html" %}
{% load custom_filter %}
{% load static %}
{% block title %}
    Home
{% endblock %}
{% block body_tag %}
    style="background-image: url('{% static "img/1.jpg" %}');"
{% endblock %}
{% block contain %}
    <div class="row mt-3">
        <div class="col">
            <div class="jumbotron text-black-50 jb">
                <h1 class="display-4 font-italic">Happy Every Day</h1>
                <p>Free access to the Internet<br></p>
            </div>
        </div>
    </div>
    <div class="row data-row">
        <div class="col-lg-4 mb-3">
            <div class="card m-2 bg-dark" style=" height: 100%;">
                <div class="card-body"><h3 class="text-capitalize text-white font-weight-light card-title font-italic">Data</h3>
                    <div class="table-responsive align-items-stretch">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>项</th>
                                <th>值</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>quota</td>
                                <td id="quota">{{ user.quota|to_mb }}{% if user.quota != -1 %}M{% endif %}</td>
                            </tr>
                            <tr>
                                <td>upload</td>
                                <td id="upload">{{ user.upload|to_mb }}M</td>
                            </tr>
                            <tr>
                                <td>download</td>
                                <td id="download">{{ user.download|to_mb }}M</td>
                            </tr>
                            <tr>
                                <td>left</td>
                                <td id="left">{{ left|to_mb }}{% if user.quota != -1 %}M{% endif %}</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                    <div role="group" class="btn-group">
                        <button class="btn btn-primary btn_reload" type="button">同步</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-5 mb-3">
            <div class="card m-2 bg-dark" style="height: 100%">
                <div class="card-body"><h4 class="card-title text-white font-weight-light font-italic">Chart</h4>
                    <canvas id="myChart" class="m-2"></canvas>
                </div>
            </div>
        </div>
        <div class="col-lg-3 mb-3">
            <div class="card m-2 bg-dark" style="height: 100%">
                <div class="card-body"><h4 class="card-title text-white font-weight-light font-italic">User</h4>
                    <div class="table-responsive mb-2">
                        <table class="table">
                            <tbody>
                            <tr>
                                <td>username</td>
                                <td id="username">{{ user.username }}</td>
                            </tr>
                            <tr>
                                <td>email</td>
                                <td id="email">{{ user.email }}</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                    <button class="btn btn-primary btn_change_password " data-toggle="modal" type="button"
                            data-target="#change_password" style="">修改密码
                    </button>
                    <button class="btn btn-primary btn_change_password " data-toggle="modal" type="button" id="Q_btn"
                            style="">生成链接
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div role="dialog" tabindex="-1" class="modal fade show" id="change_password">
        <div class="modal-dialog" role="document" style="top: 15.39%">
            <div class="modal-content shadow-lg bg-dark">
                <div class="modal-header" style="border: 0;">
                    <h3 class="modal-title text-warning font-italic font-weight-bold">Change your password</h3>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">×</span></button>
                </div>
                <div class="modal-body">
                    <form>
                        {% csrf_token %}
                        <label class="font-weight-bold text-warning">原密码</label><input type="password"
                                                                                       class="form-control mb-2"
                                                                                       name="old_password"
                                                                                       placeholder="Old Password"
                                                                                       autofocus required
                                                                                       style="background-color: rgb(40,40,40);"
                    /><label class="font-weight-bold text-warning">新密码</label><input type="password"
                                                                                     class="form-control mb-2"
                                                                                     name="new_password"
                                                                                     placeholder="New Passowrd" required
                                                                                     style="background-color: rgb(40,40,40);"
                    /><label class="font-weight-bold text-warning">确认密码</label><input type="password"
                                                                                      class="form-control"
                                                                                      placeholder="Repeat Password"
                                                                                      name="repeate_password" required
                                                                                      style="background-color: rgb(40,40,40);"
                    /></form>
                </div>
                <div class="modal-footer" style="border: 0;">
                    <button class="btn btn-light border-0 text-white-50" type="button" data-dismiss="modal"
                            style="background-color: rgb(58,62,67);">Close
                    </button>
                    <button class="btn btn-primary border-0" type="submit" style="background-color: rgb(28,35,42);"
                            id="submit_change_password">
                        Submit
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div role="dialog" tabindex="-1" class="modal fade show" id="Q_contain">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content bg-dark">
                <div class="modal-header border-0">
                    <h3 class="modal-title text-white">分享</h3>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">×</span></button>
                </div>
                <div class="modal-body">
                    <div class="row pl-4 pr-4">
                        <div class="col-lg-9">
                            <div class="row">
                                <div class="col" style="padding: 0;">
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text"
                                                  style="border-radius: .25rem 0 0 0;">密码</span>
                                        </div>
                                        <input type="text" class="form-control" id="Q_password" placeholder="输入正确的密码"/>
                                        <div class="input-group-append"></div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col" style="padding: 0;">
                                    <div class="input-group">
                                        <div class="input-group-prepend"><span class="input-group-text"
                                                                               style="border-radius: 0 0 0 .25rem;">用户</span>
                                        </div>
                                        <input type="text" class="form-control" id="Q_username"/>
                                        <div class="input-group-append"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3" style="padding:0;">
                            <button class="btn btn-primary" id="Q_generate" type="button"
                                    style="width: 100%;height: 100%;border: 1px">
                                生成
                            </button>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col" style="/*height: 200px;*/">
                            <div id="Q" style="height: 300px;"></div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer border-0">
                    <div class="input-group">
                        <div class="input-group-prepend"></div>
                        <input type="text" id="Q_url" class="form-control" readonly/>
                        <div class="input-group-append">
                            <button class="btn btn-primary" id="Q_copy" type="button">Copy</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static "css/home/home.css" %}">
    <style>
        #Q img {
            position: relative;
            left: 50%;
            top: 50%;
            transform: translate(-50%, -50%);
        }

        #Q_username, #Q_password {
            border-collapse: collapse;
        }

        #Q_username, #Q_password :focus {
            /*color: #495057;*/
            /* background-color: #fff; */
            border-color: #80bdff;
            outline: 0;
            box-shadow: 0 0 0 0
        }
    </style>
{% endblock %}
{% block js %}
    <script src="{% static "js/base/qrcode.min.js" %}"></script>
    <script src="{% static "js/base/Chart.js" %}"></script>
    <script src="{% static "js/home/home.js" %}"></script>
    <script>
        var USER_GET_URL = 'https://{{ request.META.HTTP_HOST }}{% url 'user:get_user_data'%}';
        var USER_CHANGE_PASSWORD = 'https://{{ request.META.HTTP_HOST }}{% url 'user:change_password'%}';
        var USER_NAME = '{{ user.username }}';
        var config = {
            type: 'doughnut',
            // type: 'pie',
            data: {
                datasets: [{
                    data: [
                        {{ user.upload|to_mb }},
                        {{ user.download|to_mb }},
                        {% if left != 'Infinite' %}
                            {{ left }}
                        {% endif %}
                    ],
                    backgroundColor: [
                        "#ffa800",
                        "#15aa1c",
                        {% if left != 'Infinite' %}
                            "#dcdcdc",
                        {% endif %}
                    ],
                    label: 'Dataset 1',
                    weight: 0.1,
                }],
                labels: [
                    'upload',
                    'download',
                    {% if left != 'Infinite' %}
                            'left',
                        {% endif %}
                ]
            },
            options: {
                responsive: true,
                animation: {animateScale: true},
                maintainAspectRatio: false
            }
        };
    </script>
{% endblock %}

MyTrojan/templates/user/login.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}
    Login
{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static "/css/user/login.css" %}">
{% endblock %}
{% block contain %}
    <div class="row-cols-1" style="position: relative;top: 50%;transform: translateY(-50%)">
        <form class="form-login" data="{% url "user:login" %}" method="post">
            {#    <img class="mb-4" src="/" alt="" width="72" height="72">#}
            {% csrf_token %}
            <h1 class="h3 mb-3 font-weight-normal text-center">Login</h1>
            <input type="text" id="inputEmail" class="form-control" placeholder="Email address/Account" name="username"
                   required
                   autofocus>
            <input type="password" id="inputPassword" class="form-control" placeholder="Password" name="password"
                   required>
            <div class="checkbox mb-3">
                <label>
                    <input type="checkbox" value="1" name="remember_me"> Remember me
                </label>
            </div>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Log in</button>
        </form>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static "js/user/login.js" %}"></script>
{% endblock %}

MyTrojan/templates/user/register.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}
    Register
{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static "css/user/register.css" %}">
{% endblock %}
{% block contain %}
    <div class="row-cols-1" style="position: relative;top: 50%;transform: translateY(-50%)">
        <form class="form-register" method="post" data="{% url "user:register" %}">
            <!--            <img class="mb-4" src="/" alt="" width="72" height="72">-->
            {% csrf_token %}
            <h1 class="h3 mb-3 font-weight-normal text-center">Register</h1>
            <input type="text" id="inputEmail" class="form-control" placeholder="Email address" name="email" required
                   autofocus>
            <input type="text" id="inputUsername" class="form-control" placeholder="Account" name="username" required
                   autofocus>
            <input type="password" id="inputPassword" class="form-control" placeholder="Password" name="password"
                   required>
            <input type="password" id="repeatPassword" class="form-control" placeholder="Repeat Password"
                   name="repeat_password" required>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Sign up</button>
        </form>
    </div>
{% endblock %}
{% block js %}
    <script>
        var USER_CHECK_ACCOUNT = 'https://{{ request.META.HTTP_HOST }}{% url 'user:verify_username' "replace"%}';
        var USER_CHECK_EMAIL = 'https://{{ request.META.HTTP_HOST }}{% url 'user:verify_email' "replace"%}';
    </script>
    <script src="{% static "js/user/register.js" %}"></script>
{% endblock %}